/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('./src/components/arco/Checkbox.vue')['default']
    Date: typeof import('./src/components/arco/Date.vue')['default']
    Input: typeof import('./src/components/arco/Input.vue')['default']
    Number: typeof import('./src/components/arco/Number.vue')['default']
    Password: typeof import('./src/components/arco/Password.vue')['default']
    Radio: typeof import('./src/components/arco/Radio.vue')['default']
    Select: typeof import('./src/components/arco/Select.vue')['default']
  }
}
