/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    Checkbox: (typeof import("./src/components/Checkbox.vue"))["default"];
    Date: (typeof import("./src/components/Date.vue"))["default"];
    Input: (typeof import("./src/components/Input.vue"))["default"];
    Number: (typeof import("./src/components/Number.vue"))["default"];
    Password: (typeof import("./src/components/Password.vue"))["default"];
    Radio: (typeof import("./src/components/Radio.vue"))["default"];
    Select: (typeof import("./src/components/Select.vue"))["default"];
    Test: (typeof import("./src/components/test.vue"))["default"];
  }
}
